### ISSUE TITLE
Refresh causes duplicate changelists to be added, the previous ones become empty

### ISSUE THREAD

**Issue by marcsandusky** [mjcrouch/vscode-perforce#179] opened 2020-08-26 00:15 UTC
As you can see in the image, there are multiple instances of Default Changelist followed by multiple instances of each of the changelists. All of the previous changelists have a file count of zero.
![Perforce for VSCode Issue](https://user-images.githubusercontent.com/9129463/91240312-85d69f80-e6f6-11ea-8163-68f18a97d5df.png)

**Comment by mjcrouch** [comment] 2020-08-26 08:14
Hi,

Interesting, I recall a similar issue being reported in the original extension, but I've reworked the 'refresh' logic which should prevent this. To be totally sure, did you disable / uninstall the `slevesque` extension and reload the window after disabling?

Did you refresh multiple times or just once? Does it add one for each refresh without removing the original ones?

Assuming the old extension is disabled, it would probably help to see the perforce 'output log', if you don't mind the file paths etc being shared (f1 -> "Perforce: Show Output"). And possibly check the developer tools (f1 -> "Developer: Toggle Developer Tools") to see if there are any exceptions in the developer console

Thanks

**Comment by RickWassum** [comment] 2020-08-26 21:16
Hi MJ, 

I have been experiencing the same problem as marcsandusky.  I do not have the slevesque extension installed.  I believe the problem started occurring when I installed a VSCode update that had SCM updates.  I cannot remember if it was the recent addition of the  SCM: Always Show Repositories setting or a prior update, but I believe it was within the last month.  I don't see any dev tools console errors when refreshing, and there does not appear to be anything of relevance in the Perforce Log when I refresh either.  Only a login, changes, describe, opened and fstat commands.   

Love the extension, btw, it is much appreciated.

**Comment by marcsandusky** [comment] 2020-08-26 21:34
I uninstalled the previous extension as soon as I found this one.  That has not been an issue.

This issue only occurred recently for me as well, and it had been working well until a recent update. I use code-insiders, which is updated daily, so that may be a hint. I run under Ubuntu 20.04, and I installed it manually from the .deb. The snap version from Ubuntu software has issues with the newer versions of Electron.

New duplicate entries are added for each refresh. After a few refreshes, it is easier to just restart the IDE.

I'll attach logs soon.

Thanks.

**Comment by RickWassum** [comment] 2020-08-26 21:38
I am running both the standard vscode and the insiders edition on windows using the built-in update process, and both versions exhibit the same behavior for me.

**Comment by marcsandusky** [comment] 2020-08-26 21:54
Here are the logs you requested.

[Duplicate Changelists - Perforce Log.txt](https://github.com/mjcrouch/vscode-perforce/files/5132915/Duplicate.Changelists.-.Perforce.Log.txt)
[Duplicate Changelists - Developers Console.log](https://github.com/mjcrouch/vscode-perforce/files/5132918/Duplicate.Changelists.-.Developers.Console.log)

**Comment by RickWassum** [comment] 2020-08-26 22:59
My apologies, but I will retract my previous statement that both versions exhibit the same behavior.  I just retested, and the standard vscode version is not creating duplicate entries regardless of how many times I refresh, however the vscode-insiders version continues to create additional duplicates each time I refresh.

The exact versions of each that I am running are:
Visual Studio Code - Insiders
Version: 1.49.0-insider (user setup)
Commit: 7df29b1236ecf8a21af9fe19a52923f6d69e0577
Date: 2020-08-26T07:58:02.868Z (13 hrs ago)
Electron: 9.2.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363

Visual Studio Code
Version: 1.48.2 (user setup)
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-25T10:13:11.295Z (1 day ago)
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Both are using Perforce for VS Code 4.12.0 with the same extension settings.

**Comment by mjcrouch** [comment] 2020-08-27 08:12
Thanks all for the details  - Just tried in insiders and the same thing happens for me. It doesn't happen for me in the current release 1.48.2

I know @joaomoreno has recently done a large amount of refactoring in the scm view for performance so it looks like there may be an issue with the disposal of `SourceControlResourceGroup`

**Comment by mjcrouch** [comment] 2020-08-27 09:21
raised https://github.com/microsoft/vscode/issues/105483

**Comment by mjcrouch** [comment] 2020-08-28 14:31
I've created https://github.com/microsoft/vscode/pull/105587 to fix the issue in vs code, but will leave this one open until it's merged so that the issue is still visible here until then.

Hopefully the PR is merged before the next release othwerwise everyone will have the same issue :)

**Closed** 2020-08-31 14:30 UTC
