### ISSUE TITLE
Perforce operations not working on images

### ISSUE THREAD

**Issue by maciejmatczak** [mjcrouch/vscode-perforce#124] opened 2020-04-29 10:07 UTC
**Describe the bug:**
I can't perforce edit currently opened image files, not sure if it applies for every no-code files.

**Expected behavior:**
Any opened file should be applicable for perforce operation.

**To Reproduce:**
Open image, hitting `CTRL+SHIFT+P`, choosing `Perforce: edit`, image is not marked for edit.

Output log:
Sometimes only:
```
No file selected
```
Sometimes with `extension-output`:
```
\: p4.exe 'opened' 'extension-output-%232'
\: p4.exe 'opened' 'extension-output-%233'
\: p4.exe 'edit' 'extension-output-%233'
ERROR: "Path '\\extension-output-%233' is not under client's root '<path-to-my-root>'.\r\n"
```

**Versions & Details:**
 - Perforce extension: 4.4.1
 - VSCode version: 1.44.1
 - Operating System: Windows 10
 - Perforce server details (if known):
 - Are you using a multi-root workspace?: No

**Comment by mjcrouch** [comment] 2020-04-29 10:10
thanks - when you see extension output - it normally means you have clicked in to the Perforce log before trying to run the command, so it thinks the perforce log is the active editor and tries to open that.
Will have to look into how vscode handles this kind of editor so that we can run commands on it

**Comment by mjcrouch** [comment] 2020-04-29 20:17
Unfortunately looking into it a bit further I don't think it's possible to support this with the current vs code API

The problem is the image preview is a WebView, and vscode makes these private so we don't have any information about the open file when we run this command. As far as the extension is aware there's no editor open at-all

see https://github.com/Microsoft/vscode/issues/49915

The best alternative I can think of is adding an item to the explorer context menu which would open this menu, still wouldn't help for the keyboard shortcuts though.

**Comment by mjcrouch** [comment] 2020-06-04 16:26
closing this for now as I don't think there's anything more we can do currently

**Closed by mjcrouch** 2020-06-04 16:26 UTC
Labels: bug
