### ISSUE TITLE
Perforce extension seems to be breaking the MS PowerShell Integrated Console

### ISSUE THREAD

**Issue by JimBreton** [mjcrouch/vscode-perforce#154] opened 2020-05-28 23:03 UTC
**Describe the bug:**

Since the latest revision of this Perforce extension, the PowerShell Integrated Console (from the MS PowerShell extension) crashes upon loading after opening a PowerShell script.

(This didn't happen in the immediately prior release, and it doesn't look like the MS extension has been updated in the relevant timeframe.)

**Expected behavior:**

No PIC crashes. :)

![image](https://user-images.githubusercontent.com/45986932/83202120-eca6e580-a114-11ea-89d4-b07a8d05aa6b.png)

**To Reproduce:**

With both extensions (Perforce and PowerShell) loaded, open a PowerShell script in the editor, which will launch the PowerShell Integrated Console.  After a few seconds the console will crash with error, "The terminal process terminated with exit code: 5".

**Versions & Details:**
 - Perforce extension: 4.8.2
 - VSCode version: 1.45.1
 - Operating System: Windows 10 Enterprise
 - Perforce server details (if known): P4D/NTX64/2019.1/1915891 (2020/02/09)
 - Are you using a multi-root workspace?: No

**Additional context**
What's interesting is it seems to only happen when Perforce is logged in, and when the P4 extension is aware of that.

For example, if I open the PIC (while logged out of P4) and then log in manually from that CLI (`p4 login`), there is no issue; it's not unless the VS Code extension 'knows' I'm logged in that the console crashes.  Maybe something it's trying to set in the shell that the PIC doesn't like?

```
Please open view -> Output, select "Perforce Log" from the dropdown and paste it here, if possible / relevant
```

</details>

**Comment by mjcrouch** [comment] 2020-05-29 07:19
Thanks - seems strange. Unfortunately I haven't been able to reproduce it by following your steps.
I don't believe I've changed anything significant in this area

If you don't mind, could you try installing an earlier version of the extension (e.g. 4.7.0 I suppose. You can do this by clicking on the gear icon on the extension and choosing "install another version"). IIRC there was a vscode release at around the same time, so I'd like to rule out whether something in vscode has changed.

I'd also like to know if there's anything in the perforce output log that looks like an obvious error that happens at the same time? (there's probably quite a lot of output at the point that you log in...)

**Comment by JimBreton** [comment] 2020-05-29 20:33
Thanks for following up!

Good thought.  I downgraded to 4.7.0 and the issue went away; so then I went up to 4.8.1, still no issue.  But then when I went back to 4.8.2, it started happening again.

Saw your other questions as well, will follow up on those tonight when I have a bit more time.  Ty!

**Comment by mjcrouch** [comment] 2020-05-29 20:37
also now I think of it the powershell extension has its own output logs as well which might give more clues as to *what* is returning exit code 5

**Comment by mjcrouch** [comment] 2020-05-29 20:49
Thoughts on this - the only thing that really changed between those versions as that I switched how we print out perforce content, from implementing a `TextDocumentContentProvider` to implementing a `FileSystemProvider`

This is used when you diff a file, open a depot file etc, and also when it gets the underlying text for gutter diffs. Using a `FileSystemProvider` is the only way to control the editor titles icur

In order to do that I also had to implement a bunch of other functions that handle other OS operations like `writeFile` `createDirectory`. For this I followed the approach used by GitLens which is basically just return a NoPermissions exception, because this only ever provides readonly documents.
The suspicious thing here is that exit code 5 is an access denied windows system code, which probably matches the NoPermissions exception... Not sure what it would be doing that would require it to do any of those kinds of operations though, so it may not be the thing, but there's not much else to go on..

**Comment by JimBreton** [comment] 2020-05-29 23:02
OK, here is the last few lines of the PowerShell Extension Logs.  I just included the last few because the last line is the only one that actually differs between 4.8.1 where it doesn't crash out.  (Even the "invalid version" log occurs in a normal run.)

Also I'm manually typing this out because it's coming from an environment that is intentionally difficult to copy from, so I'm omitting timestamps and trying to be succinct as this is all by hand. :)

[NORMAL] - Connecting to language service on pipe \\.\pipe\PSES_<path>....
[NORMAL] - Language service connected.
[WARNING] - Invalid Version: null
[NORMAL] - powershell.exe terminated or terminal UI was closed

I also noted the PowerShell Editor Services output which might be even more useful as it may tie back to what you were discussing in your last comment:

[Info  - <timestamp>] Microsoft.PowerShell.EditorServices.Services.AnalysisService: PSScriptAnalyzer settings file not found.  Falling back to default rules
[Error - <timestamp>] Connection to server got closed.  Server will not be restarted.
[Error - <timestamp>] Request textDocument/documentSymbol failed.
Error: connection got disposed.

Then there's a couple more output blocks similar to that above, along with what appear to be stack traces.  But the important pieces may be the "Request ... failed" parts.  Aside from the one shown above, the following also occur:

Request textDocument/codeAction failed.
Error: connection got disposed.

Request textDocument/foldingRange failed.
Error: connection got disposed.

Request textDocument/codeLens failed.
Error: connection got disposed.

I hope that helps in some way.  If it still isn't clarifying the issue I'll see if I can do any more fiddling to narrow it down.  Thank you.

**Comment by mjcrouch** [comment] 2020-05-30 12:01
a quick grep of powershell extension and vscode source, the "the terminal process exited" error is actually in the [vscode source ](https://github.com/microsoft/vscode/blob/caa19dc534ba50efd67e20a193d2bae1eb0ca026/src/vs/workbench/contrib/debug/browser/debugTaskRunner.ts#L85)

Interestingly that code area seems to be relating to preLaunchTasks - do you have anything like that configured in your launch.json?

**Comment by mjcrouch** [comment] 2020-05-31 08:08
ok, I've managed to reproduce pretty much this - it only happens when I am viewing a powershell script that has been submitted to the depot. Also I get error code 2 instead of 5

I can't see anything wrong with the results of our FileSystemProvider calls.
My theory is that the PowerShell extension is doing some processing on all powershell scripts it finds open.
Because we provide gutter diffs for the powershell scripts by providing a virtual 'file', it applies the same processing to that, and then fails for whatever reason. I'll see if I can find out why

**Comment by mjcrouch** [comment] 2020-05-31 08:53
ok - I downloaded the source for powershell extension, got it to run... issue doesn't reproduce!

Tried installing "PowerShell Preview" instead of powershell, when I use the preview build it no longer crashes - so I believe this issue will resolve itself soon.

Looking through the preview changelog, I think the fix for this was probably "Move to Omnisharp lib 0.17.0". I say this not specifically because of this linked issue https://github.com/PowerShell/vscode-powershell/issues/1283 which has a very similar error, but because now when using the preview extension, in the PowerShell editor service logs I see an exception relating to the paths we're using to get revisions information into the titles, which it's not able to parse. This error is in OmniSharp.Extensions.LanguageServer.Server.LspRequestRouter - so I assume something has been updated to prevent this from crashing.

So - could you try using the PowerShell preview extension (disable PowerShell) and see if it resolves the issue?

**Comment by JimBreton** [comment] 2020-06-01 14:33
That's some great feedback.  I haven't done the PoSh Preview thing yet, but I did notice that 4.9.0 of your P4 extension has been released; after updating to that, the issue is resolved!  Is this expected, or would there still be value in me trying 4.8.2 + PoSh Preview?  If so, I think I'll be able to give that a whirl tonight.

**Comment by mjcrouch** [comment] 2020-06-01 15:26
I don't think I changed anything that would affect this - just tried the powershell non-preview extension with my latest build and it coninues to crash for me.

My experience is it probably depends on exactly which file you have open in the editor, specifically have to have a powershell script that is in perforce, so don't know if that may be something to do with it?

**Comment by JimBreton** [comment] 2020-06-02 22:43
My last post could have been a False Negative, as it started occurring again today (even with 4.9.0), so it calls into question whether I was logged into P4 when it _wasn't_ occurring, which was one of my original criteria. 🙄

Anyway I went ahead as you suggested and installed the PoSh Preview extension and indeed, the issue seems to not occur here

I'm good with closing the case at this point unless you need anything further from me.  Thanks!

**Comment by mjcrouch** [comment] 2020-06-03 07:01
closing for now - we can reopen if it breaks again :)

**Closed by mjcrouch** 2020-06-03 07:01 UTC
Labels: bug
