### ISSUE TITLE
[vscode 1.76.0] Connection not opened until manual sync

### ISSUE THREAD

**Issue by a5ehren** [mjcrouch/vscode-perforce#251] opened 2023-03-02 13:05 UTC
**Describe the bug:**
No files are displayed in the SCM tab until I do a manual sync from the extension. I do not know if this is a purposeful extension API change by MS that requires an update or a regression in vscode.

**Expected behavior:**
Tab should populate with my workspace upon opening, like it did in vscode 1.75.2.

**To Reproduce:**
Open workspace with p4client configured, go to SCM tab and see that it is empty.

**Versions & Details:**
 - Perforce extension: 4.15.5
 - VSCode version: 1.76.0
 - Operating System: Ubuntu Linux 22.10
 - Perforce server details (if known): <redacted for employment reasons>
 - Are you using a multi-root workspace?: No

**Additional context**

<cannot share due to employer info>

**Comment by mjcrouch** [comment] 2023-03-02 13:39
thanks for reporting! I just had a quick look and can reproduce - it looks like a bug in the vscode API where a previously released API has been marked as experimental. I've reported @ https://github.com/microsoft/vscode/issues/175888

**Comment by mjcrouch** [comment] 2023-03-03 16:26
closing as I worked around the vs code problem in 4.15.7

**Closed by mjcrouch** 2023-03-03 16:26 UTC
Labels: bug
